### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by stefangachter** [Mobsya/thymio-scratchx#20]
I extended the thymio_extension_beginner.js with de: section for blocks and menus and pushed the changes to github. I tried to test it, but blocks do not appear anymore, independent of language selection. Could somebody else test it?

Changes are here:
https://github.com/stefangachter/thymio-scratchx/blob/gh-pages/thymio_extension_beginner.js

**Comment by stefangachter** [comment]
The following links load the correct language version:
http://scratchx.org/?url=https://cdn.jsdelivr.net/gh/stefangachter/thymio-scratchx@gh-pages/thymio_extension_beginner.js&lang=en#scratch
http://scratchx.org/?url=https://cdn.jsdelivr.net/gh/stefangachter/thymio-scratchx@gh-pages/thymio_extension_beginner.js&lang=fr#scratch
http://scratchx.org/?url=https://cdn.jsdelivr.net/gh/stefangachter/thymio-scratchx@gh-pages/thymio_extension_beginner.js&lang=it#scratch

But for de it fails:
http://scratchx.org/?url=https://cdn.jsdelivr.net/gh/stefangachter/thymio-scratchx@gh-pages/thymio_extension_beginner.js&lang=de#scratch

Because cdn.jsdelivr.net does not provide the latest file...

**Comment by stefangachter** [comment]
Still the same issue, github and jsdelivr files arre up-to-date, but ScratchX loads an outdated version of thymio_extension_beginner.js, see screenshots below. I am wondering how extension development is best done for ScratchX.

![スクリーンショット 2019-04-06 7 06 01](https://user-images.githubusercontent.com/7974580/55665186-10d1a400-583b-11e9-9a58-08edba2fe6e3.png)

![スクリーンショット 2019-04-06 7 06 12](https://user-images.githubusercontent.com/7974580/55665190-1b8c3900-583b-11e9-8e79-69fecc018dea.png)

![スクリーンショット 2019-04-06 7 06 27](https://user-images.githubusercontent.com/7974580/55665193-2777fb00-583b-11e9-9413-cd60ba7e93d3.png)

![スクリーンショット 2019-04-06 7 06 58](https://user-images.githubusercontent.com/7974580/55665198-32329000-583b-11e9-922e-6fca00c71dd1.png)

**Comment by mbonani** [comment]
Hello,
it seems that the link you give is working for me:
![image](https://user-images.githubusercontent.com/1000934/55729326-3961c580-5a16-11e9-8baa-60143305b31d.png)

Do you have problem perhaps of cache? You have to refresh correctly your browser.

**Comment by stefangachter** [comment]
Thanks for testing!
I tried again. It does not work with Safari, because of some access control checks. But it works with Firefox with the link
http://scratchx.org/?url=https://cdn.jsdelivr.net/gh/stefangachter/thymio-scratchx@gh-pages/thymio_extension_beginner.js&lang=de#scratch

What still not works is loading the thymio_extension_beginner.js from local drive.

**Comment by mbonani** [comment]
Yes most of recent browser do not accept mix of http: and https: pages. 
Anyway scratchx is depreciated and we move on scratch 3. We will release soon a new version.
We already have a German translation for the blocks (not online) your are welcome to proof read it. 
https://github.com/Mobsya/scratch-vm/blob/develop/src/extensions/scratch3_thymio/lang/de.js
Kind regards

**Comment by stefangachter** [comment]
Thanks for the advice. Oh, I was not aware of the recent development.
I took a look at the German translation. Here, my suggestion:
https://github.com/stefangachter/scratch-vm/blob/german-translation/src/extensions/scratch3_thymio/lang/de.js
Wording is somewhat different from French or English and has to be cross-checked with the block layout.
